site_name: CODEPREP documentation
pages:
  - Home: 'index.md'
  - Bookを作る:
    - 'sample bookを作る': 'getstart/how-to-make-book.md'
    - 'bookの作り方': 'getstart/get-start.md'
  - ご契約について :
      - 'ご契約について': 'contract/index.md'
theme: yeti
